# Generated by Django 5.1.5 on 2025-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_relationships",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_tokens",
                to="token_blacklist.outstandingtoken",
            ),
        ),
    ]
