# Generated by Django 5.1.5 on 2025-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_specialty_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
