# Generated by Django 5.1.5 on 2025-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_doctor_license_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "day_of_week", "start_time", "end_time")},
        ),
    ]
