# Generated by Django 5.1.5 on 2025-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_profile_blood_type_profile_consultation_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
